name: Java CD

on:
  push:
    branches:
      - 'main-dumpster'

jobs:
  Upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Determine new version
      id: ver
      uses: paulhatch/semantic-version@v4
      with:
        tag_prefix: "v"
        major_pattern: "breaking change"
        minor_pattern: "^feat:"
        format: "${major}.${minor}.${patch}-${increment}"
        change_path: "src/main"
    - name: Build with Ant
      run: ant -noinput -buildfile build.xml
    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        artifacts: ./out/BearInMind.jar
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ steps.ver.outputs.version }}
        commit: 'main-dumpster'