name: Java CD

on:
  push:
    branches:
      - 'main-dumpster'

jobs:
  Upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Ant
      run: ant -noinput -buildfile build.xml
    - name: Create release
      id: rp
      uses: google-github-actions/release-please-action@v3
      with:
        command: github-release
        release-type: java
        package-name: BearInMind
        default-branch: main-dumpster
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      if: ${{ steps.rp.outputs.release_created }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.rp.outputs.upload_url }}
        asset_path: ./out/BearInMind.java
        asset_name: BearInMind-v${{ steps.rp.outputs.major }}.${{ steps.rp.outputs.minor }}.${{ steps.rp.outputs.patch }}.jar
        asset_content_type: application/java-archive