name: Java CD

on:
  release:
    types: [published]

jobs:
  Upload:
    steps:
    - uses: actions/checkout@v3
      with:
        ref: 'main-dumpster'
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Ant
      run: ant -noinput -buildfile build.xml
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ release.upload_url }}
        asset_path: out/BearInMind.java
        asset_name: BearInMind-${{ release.tag_name }}.jar
        asset_content_type: application/java-archive