name: Java CD

on:
  push:
    branches:
      - 'main-dumpster'

jobs:
  Upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Ant
      run: ant -noinput -buildfile build.xml
    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        artifacts: ./out/BearInMind.java
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: '1.0.0'
        commit: 'main-dumpster'