name: Release PR generation

on:
  push:
    branches: [ "development" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Create release PR
      uses: google-github-actions/release-please-action@v3
      with:
        release-type: simple
        package-name: BearInMind
        default-branch: main-dumpster
